league_id:  #Needs to be approved here https://www.dota2.com/league/0/list 
game_mod: 16 # 16 = Captains Draft, 2 = Captains Mode
lobby_size: 10
game_name_prefix: 
discord_league_admin_role_name: 
league_starting_mmr: 1000
lobby_timeout: 300 #seconds